color: null
description: null
fieldLayouts:
  12f8c6de-4ca2-4da7-b1cb-827f4e01968d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-29T01:28:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc37d22a-3bb3-4fcb-8b7b-2cee8691d5c6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-30T01:38:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: abca8568-b497-484e-b4d3-5fe77d0d18dd # Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a1e0f44-450f-4411-ac10-d5c3c676a549
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T01:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1681a684-620d-404c-a918-6af20caa8b8b # Business Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0b232e8-582d-4134-866c-0df5c8676231
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T01:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 937faf23-8b1b-469b-9235-401505a750f2 # Business Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 064e31eb-3259-47e6-ad42-baa6e07c6bc0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T01:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb7cd503-f6ff-480a-b797-4ddb4f3ac9a3 # Business Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a71ac0d-c816-4eb2-b03c-3084d1f01fbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T01:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 90c4ffa5-83bb-4af6-8837-6ad5bf1c323c # Business Phone
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb834a18-7534-4ad0-824f-2fef5b3fcfca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T01:35:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b441d323-0b33-4f14-95c6-153d91a1674d # Business Website
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 458ec52d-1155-45bd-a853-39bf9d61d8d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-19T15:29:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21d5b2e7-055d-41a3-8842-86406bf86748 # One Special (same each month)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a34addb2-7670-45bd-a29a-58fce408bc6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-19T15:56:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d4bb8a19-094e-48c4-b6ca-37154e3fc329 # Monthly Specials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6668dc84-fd32-4991-af58-5e21b4a37465
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-19T15:52:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2380efb4-0a40-440f-9ddf-b81d64af40d0
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 977c178a-31aa-4787-9a81-b8bc8212293a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-29T03:15:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bbcf789-77a3-45b6-b5c3-3e7b2f518bcb
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 081ff5c0-c59f-4323-abaf-289ab43b6295
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d46d188c-2f64-44c8-8aaa-c0ef97964401
        userCondition: null
handle: business
hasTitleField: true
icon: null
name: Business
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
