altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8f2c97e0-7ee4-483c-9d4f-108e15699bc8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-29T01:36:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c3c168f4-14fb-4d22-9f89-ce6eb5b459d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9c173c2-b7cf-442b-b899-51d82ad30990
        userCondition: null
fs: uploads
handle: business
name: Business
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
