columnSuffix: null
handle: monthlySpecials
instructions: 'Enter monthly specials.'
name: 'Monthly Specials'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Month
            -
              - handle
              - month
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Special
            -
              - handle
              - special
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - January
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - February
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - March
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - April
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - May
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - June
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - July
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - August
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - September
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - October
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - November
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - December
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
